language: rust
rust: nightly
before_script:
  - nvm install 8
  - rustup target add wasm32-unknown-unknown
  - cargo install wasm-bindgen-cli
  - npm install
  - npm run build
script:
  - npm test
notifications:
  email:
    on_success: never
    on_failure: change
