[package]
name = "deadstones"
version = "2.0.0"
authors = ["Yichuan Shen <shen.yichuan@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
wasm-bindgen = "0.2.8"

[profile.release]
lto = true
opt-level = 's'
